model_name_or_path: /home/narulanavya3/hf_models/Qwen2.5-3B-Instruct
trust_remote_code: true
template: qwen
dataset: yourdata15k
dataset_dir: /home/narulanavya3/LLaMA-Factory/data
cutoff_len: 4096
train_on_prompt: false
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 32
lora_dropout: 0.05
output_dir: /home/narulanavya3/outputs/qwen25-3b-sft-lora-a100-normal
num_train_epochs: 3
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2e-4
lr_scheduler_type: cosine
warmup_ratio: 0.03
weight_decay: 0.0
logging_steps: 20
save_steps: 200
save_total_limit: 3
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
report_to: none
ddp_timeout: 18000
stage: sft
do_train: true
resume_from_checkpoint: false
max_steps: -1
